### ISSUE TITLE
When I use the translation feature of the Edge browser, the document web page crashes!

### ISSUE THREAD

**Issue by masx200** [netbirdio/docs#162]
When I use the translation feature of the Edge browser, the document web page crashes!

https://docs.netbird.io/how-to/routing-traffic-to-private-networks

![屏幕截图 2024-03-08 203913](https://github.com/netbirdio/docs/assets/34191203/fbc780a8-5df3-47f4-8eb4-c5e889289df4)

**Comment by masx200** [comment]
````
107Third-party cookie will be blocked. Learn more in the Issues tab.
app.js:59 SyntaxError: Unexpected token 'F', "Find somet"... is not valid JSON
    at JSON.parse (<anonymous>)
    at window.onload (app.js:59:731)
VM83:405 Edge Translation started
how-netbird-works:1  Error handling response: TypeError: Cannot read properties of undefined (reading 'isM3U8Video')
    at chrome-extension://popomkonnjgcdagdhgcpcekbdeoibglc/js/xl-content.js:1:14139
how-netbird-works:1  Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
framework-5666885447fdc3cc.js:9  DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ak (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:85039)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86279)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86736)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86541)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86541)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86736)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
Mi @ framework-5666885447fdc3cc.js:9
main-0907e39cadfa5f85.js:1  DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ak (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:85039)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86279)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86736)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86541)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86541)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86736)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
renderError @ main-0907e39cadfa5f85.js:1
main-0907e39cadfa5f85.js:1  A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
renderError @ main-0907e39cadfa5f85.js:1
framework-5666885447fdc3cc.js:9  DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ak (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:85039)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86279)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86736)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86541)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86541)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86736)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
Mi @ framework-5666885447fdc3cc.js:9
main-0907e39cadfa5f85.js:1  DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ak (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:85039)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86279)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86736)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86541)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86541)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
    at ek (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86736)
    at dk (https://docs.netbird.io/docs-static/_next/static/chunks/framework-5666885447fdc3cc.js:9:86428)
renderError @ main-0907e39cadfa5f85.js:1
main-0907e39cadfa5f85.js:1  A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
renderError @ main-0907e39cadfa5f85.js:1
main-0907e39cadfa5f85.js:1  Error rendering page:  Error: Cancel rendering route
    at _ (main-0907e39cadfa5f85.js:1:14420)
    at main-0907e39cadfa5f85.js:1:14372
    at new Promise (<anonymous>)
    at doRender (main-0907e39cadfa5f85.js:1:14349)
    at main-0907e39cadfa5f85.js:1:12486
(匿名) @ main-0907e39cadfa5f85.js:1
```
